---
apiVersion: v1
data:
  POST_URL: {{ .Values.env.post_url | b64enc }}
  GCP_CREDENTIALS_FILE: {{ .Values.env.gcp_credentials_file | b64enc }}
  GCP_TOPIC_NAME: {{ .Values.env.gcp_topic_name | b64enc }}
  GCP_CREATE_TOPIC: {{ .Values.env.gcp_create_topic | b64enc }}
  GCP_SUBSCRIPTION_NAME: {{ .Values.env.gcp_subscription_name | b64enc }}
  GCP_CREATE_SUBSCRIPTION: {{ .Values.env.gcp_create_subscription | b64enc }}
  GCP_PROJECT_ID: {{ .Values.env.gcp_project_id | b64enc }}
kind: Secret
metadata:
  name: pubsub2http-environment

---
apiVersion: v1
data:
  auth.json: |-
    {{ .Files.Get .Values.gcp.auth_file | b64enc }}
kind: Secret
metadata:
  name: pubsub2http-auth